import { planDate } from "./date.js";
import type { TaskSeed } from "./types.js";

export const sprintOneDayOne: TaskSeed[] = [
  {
    sourceKey: "s1-d1-majority-element-i",
    sprintName: "Sprint 1",
    title: "Majority Element-I",
    notes: "Sprint 1 - Day 1",
    date: planDate(9, 26),
    dayNumber: 1,
    difficulty: "Easy",
    estimatedMinutes: 15,
    timeSpentSeconds: 157,
    completed: true,
  },
  {
    sourceKey: "s1-d1-kadanes-algorithm",
    sprintName: "Sprint 1",
    title: "Kadane's Algorithm",
    notes: "Sprint 1 - Day 1",
    date: planDate(9, 26),
    dayNumber: 1,
    difficulty: "Medium",
    estimatedMinutes: 21,
    timeSpentSeconds: 552,
    completed: true,
  },
  {
    sourceKey: "s1-d1-majority-element-ii",
    sprintName: "Sprint 1",
    title: "Majority Element-II",
    notes: "Sprint 1 - Day 1",
    date: planDate(9, 26),
    dayNumber: 1,
    difficulty: "Medium",
    estimatedMinutes: 25,
  },
  {
    sourceKey: "s1-d1-maximum-product-subarray",
    sprintName: "Sprint 1",
    title: "Maximum Product Subarray in an Array",
    notes: "Sprint 1 - Day 1",
    date: planDate(9, 26),
    dayNumber: 1,
    difficulty: "Medium",
    estimatedMinutes: 18,
  },
  {
    sourceKey: "s1-d1-sort-zeros-ones-twos",
    sprintName: "Sprint 1",
    title: "Sort an array of 0's 1's and 2's",
    notes: "Sprint 1 - Day 1",
    date: planDate(9, 26),
    dayNumber: 1,
    difficulty: "Medium",
    estimatedMinutes: 24,
  },
  {
    sourceKey: "s1-d1-three-sum",
    sprintName: "Sprint 1",
    title: "3 Sum",
    notes: "Sprint 1 - Day 1",
    date: planDate(9, 26),
    dayNumber: 1,
    difficulty: "Medium",
    estimatedMinutes: 37,
  },
  {
    sourceKey: "s1-d1-next-permutation",
    sprintName: "Sprint 1",
    title: "Next Permutation",
    notes: "Sprint 1 - Day 1",
    date: planDate(9, 26),
    dayNumber: 1,
    difficulty: "Medium",
    estimatedMinutes: 26,
  },
  {
    sourceKey: "s1-d1-four-sum",
    sprintName: "Sprint 1",
    title: "4 Sum",
    notes: "Sprint 1 - Day 1",
    date: planDate(9, 26),
    dayNumber: 1,
    difficulty: "Medium",
    estimatedMinutes: 27,
  },
  {
    sourceKey: "s1-d1-merge-sorted-arrays",
    sprintName: "Sprint 1",
    title: "Merge two sorted arrays without extra space",
    notes: "Sprint 1 - Day 1",
    date: planDate(9, 26),
    dayNumber: 1,
    difficulty: "Medium",
    estimatedMinutes: 32,
  },
  {
    sourceKey: "s1-d1-trapping-rainwater",
    sprintName: "Sprint 1",
    title: "Trapping Rainwater",
    notes: "Sprint 1 - Day 1",
    date: planDate(9, 26),
    dayNumber: 1,
    difficulty: "Medium",
    estimatedMinutes: 29,
  },
  {
    sourceKey: "s1-d1-count-inversions",
    sprintName: "Sprint 1",
    title: "Count Inversions",
    notes: "Sprint 1 - Day 1",
    date: planDate(9, 26),
    dayNumber: 1,
    difficulty: "Medium",
    estimatedMinutes: 23,
  },
  {
    sourceKey: "s1-d1-reverse-pairs",
    sprintName: "Sprint 1",
    title: "Reverse Pairs",
    notes: "Sprint 1 - Day 1",
    date: planDate(9, 26),
    dayNumber: 1,
    difficulty: "Medium",
    estimatedMinutes: 31,
  },
  {
    sourceKey: "s1-d1-two-sum",
    sprintName: "Sprint 1",
    title: "Two Sum",
    notes: "Sprint 1 - Day 1",
    date: planDate(9, 26),
    dayNumber: 1,
    difficulty: "Medium",
    estimatedMinutes: 17,
  },
  {
    sourceKey: "s1-d1-longest-consecutive-sequence",
    sprintName: "Sprint 1",
    title: "Longest Consecutive Sequence in an Array",
    notes: "Sprint 1 - Day 1",
    date: planDate(9, 26),
    dayNumber: 1,
    difficulty: "Medium",
    estimatedMinutes: 22,
  },
];
