import { planDate } from "./date.js";
import type { TaskSeed } from "./types.js";

export const sprintOneDay5: TaskSeed[] = [
  {
    sourceKey: "s1-d5-1",
    sprintName: "Sprint 1",
    title: "Palindrome partitioning",
    notes: "Sprint 1 - Day 5",
    date: planDate(9, 30),
    dayNumber: 5,
    difficulty: "Medium",
    estimatedMinutes: 18,
  },
  {
    sourceKey: "s1-d5-2",
    sprintName: "Sprint 1",
    title: "Word Search",
    notes: "Sprint 1 - Day 5",
    date: planDate(9, 30),
    dayNumber: 5,
    difficulty: "Medium",
    estimatedMinutes: 19,
  },
  {
    sourceKey: "s1-d5-3",
    sprintName: "Sprint 1",
    title: "N Queen",
    notes: "Sprint 1 - Day 5",
    date: planDate(9, 30),
    dayNumber: 5,
    difficulty: "Medium",
    estimatedMinutes: 24,
  },
  {
    sourceKey: "s1-d5-4",
    sprintName: "Sprint 1",
    title: "Sudoku Solver",
    notes: "Sprint 1 - Day 5",
    date: planDate(9, 30),
    dayNumber: 5,
    difficulty: "Medium",
    estimatedMinutes: 31,
  },
  {
    sourceKey: "s1-d5-5",
    sprintName: "Sprint 1",
    title: "Find Middle of Linked List",
    notes: "Sprint 1 - Day 5",
    date: planDate(9, 30),
    dayNumber: 5,
    difficulty: "Medium",
    estimatedMinutes: 14,
  },
  {
    sourceKey: "s1-d5-6",
    sprintName: "Sprint 1",
    title: "Find the intersection point of Y LL",
    notes: "Sprint 1 - Day 5",
    date: planDate(9, 30),
    dayNumber: 5,
    difficulty: "Medium",
    estimatedMinutes: 32,
  },
  {
    sourceKey: "s1-d5-7",
    sprintName: "Sprint 1",
    title: "Check if LL is palindrome or not",
    notes: "Sprint 1 - Day 5",
    date: planDate(9, 30),
    dayNumber: 5,
    difficulty: "Medium",
    estimatedMinutes: 20,
  },
  {
    sourceKey: "s1-d5-8",
    sprintName: "Sprint 1",
    title: "Detect a loop in LL",
    notes: "Sprint 1 - Day 5",
    date: planDate(9, 30),
    dayNumber: 5,
    difficulty: "Medium",
    estimatedMinutes: 20,
  },
];
