import { createDayTasks } from "./types";

export const sprintSevenDay1 = createDayTasks(7, 1, 11, 3, [
  ["Highest Order Placing Customer", 15],
  ["Frequent Actor-Director Duos", 15],
  ["Large Classes", 15],
  ["Email Duplicates", 15],
  ["Merging Query Results", 17],
  ["UNION", 8],
  ["UNION ALL", 1],
  ["Difference Between UNION and UNION ALL", 4],
  ["Intersection", 6],
  ["Combine Active and Archived Users", 15],
  ["Merge Recent Orders from Multiple Sources", 15],
  ["Combine Sales Records Without Deduplication", 15],
  ["Reshape Products Data", 15],
  ["Joins Deep Dive", 10],
  ["RIGHT JOIN", 23],
  ["ON vs. WHERE", 15],
  ["LEFT JOIN", 6],
  ["INNER JOIN", 8],
  ["FULL OUTER JOIN", 10],
  ["CROSS JOIN", 2],
  ["IMPLICIT JOIN", 4],
  ["SELF JOIN", 70],
  ["NATURAL JOIN", 5],
  ["Employees and Their Departments", 15],
  ["Customer Orders Overview", 15],
  ["Employees With Confirmed Salary Records", 15],
]);
