import { planDate } from "./date";
import type { TaskSeed } from "./types";

export const sprintOneDayTwo: TaskSeed[] = [
  {
    sourceKey: "s1-d2-longest-subarray-sum-k",
    sprintName: "Sprint 1",
    title: "Longest subarray with sum K",
    notes: "Sprint 1 - Day 2",
    date: planDate(9, 27),
    dayNumber: 2,
    difficulty: "Medium",
    estimatedMinutes: 40,
  },
  {
    sourceKey: "s1-d2-count-subarrays-given-sum",
    sprintName: "Sprint 1",
    title: "Count subarrays with given sum",
    notes: "Sprint 1 - Day 2",
    date: planDate(9, 27),
    dayNumber: 2,
    difficulty: "Medium",
    estimatedMinutes: 22,
  },
  {
    sourceKey: "s1-d2-count-subarrays-xor-k",
    sprintName: "Sprint 1",
    title: "Count subarrays with given xor K",
    notes: "Sprint 1 - Day 2",
    date: planDate(9, 27),
    dayNumber: 2,
    difficulty: "Medium",
    estimatedMinutes: 23,
  },
  {
    sourceKey: "s1-d2-find-peak-element",
    sprintName: "Sprint 1",
    title: "Find peak element",
    notes: "Sprint 1 - Day 2",
    date: planDate(9, 27),
    dayNumber: 2,
    difficulty: "Medium",
    estimatedMinutes: 32,
  },
  {
    sourceKey: "s1-d2-minimum-rotated-array",
    sprintName: "Sprint 1",
    title: "Find minimum in Rotated Sorted Array",
    notes: "Sprint 1 - Day 2",
    date: planDate(9, 27),
    dayNumber: 2,
    difficulty: "Medium",
    estimatedMinutes: 15,
  },
  {
    sourceKey: "s1-d2-search-rotated-array-ii",
    sprintName: "Sprint 1",
    title: "Search in rotated sorted array-II",
    notes: "Sprint 1 - Day 2",
    date: planDate(9, 27),
    dayNumber: 2,
    difficulty: "Medium",
    estimatedMinutes: 12,
  },
  {
    sourceKey: "s1-d2-single-element-sorted-array",
    sprintName: "Sprint 1",
    title: "Single element in sorted array",
    notes: "Sprint 1 - Day 2",
    date: planDate(9, 27),
    dayNumber: 2,
    difficulty: "Medium",
    estimatedMinutes: 22,
  },
  {
    sourceKey: "s1-d2-search-2d-matrix-ii",
    sprintName: "Sprint 1",
    title: "Search in 2D matrix - II",
    notes: "Sprint 1 - Day 2",
    date: planDate(9, 27),
    dayNumber: 2,
    difficulty: "Medium",
    estimatedMinutes: 15,
  },
  {
    sourceKey: "s1-d2-find-peak-element-ii",
    sprintName: "Sprint 1",
    title: "Find Peak Element - II",
    notes: "Sprint 1 - Day 2",
    date: planDate(9, 27),
    dayNumber: 2,
    difficulty: "Medium",
    estimatedMinutes: 20,
  },
  {
    sourceKey: "s1-d2-nth-root",
    sprintName: "Sprint 1",
    title: "Find Nth root of a number",
    notes: "Sprint 1 - Day 2",
    date: planDate(9, 27),
    dayNumber: 2,
    difficulty: "Medium",
    estimatedMinutes: 20,
  },
  {
    sourceKey: "s1-d2-koko-eating-bananas",
    sprintName: "Sprint 1",
    title: "Koko eating bananas",
    notes: "Sprint 1 - Day 2",
    date: planDate(9, 27),
    dayNumber: 2,
    difficulty: "Medium",
    estimatedMinutes: 20,
  },
  {
    sourceKey: "s1-d2-aggressive-cows",
    sprintName: "Sprint 1",
    title: "Aggressive Cows",
    notes: "Sprint 1 - Day 2",
    date: planDate(9, 27),
    dayNumber: 2,
    difficulty: "Medium",
    estimatedMinutes: 26,
  },
  {
    sourceKey: "s1-d2-book-allocation",
    sprintName: "Sprint 1",
    title: "Book Allocation Problem",
    notes: "Sprint 1 - Day 2",
    date: planDate(9, 27),
    dayNumber: 2,
    difficulty: "Medium",
    estimatedMinutes: 27,
  },
  {
    sourceKey: "s1-d2-matrix-median",
    sprintName: "Sprint 1",
    title: "Matrix Median",
    notes: "Sprint 1 - Day 2",
    date: planDate(9, 27),
    dayNumber: 2,
    difficulty: "Medium",
    estimatedMinutes: 23,
  },
  {
    sourceKey: "s1-d2-kth-element-two-sorted-arrays",
    sprintName: "Sprint 1",
    title: "Kth element of 2 sorted arrays",
    notes: "Sprint 1 - Day 2",
    date: planDate(9, 27),
    dayNumber: 2,
    difficulty: "Medium",
    estimatedMinutes: 10,
  },
];
