import { planDate } from "./date";
import type { TaskSeed } from "./types";

export const sprintOneDay4: TaskSeed[] = [
  {
    sourceKey: "s1-d4-1",
    sprintName: "Sprint 1",
    title: "Minimum Window Substring",
    notes: "Sprint 1 - Day 4",
    date: planDate(9, 29),
    dayNumber: 4,
    difficulty: "Medium",
    estimatedMinutes: 26,
  },
  {
    sourceKey: "s1-d4-2",
    sprintName: "Sprint 1",
    title: "Number of Substrings Containing All Three Characters",
    notes: "Sprint 1 - Day 4",
    date: planDate(9, 29),
    dayNumber: 4,
    difficulty: "Medium",
    estimatedMinutes: 19,
  },
  {
    sourceKey: "s1-d4-3",
    sprintName: "Sprint 1",
    title: "Binary Subarrays With Sum",
    notes: "Sprint 1 - Day 4",
    date: planDate(9, 29),
    dayNumber: 4,
    difficulty: "Medium",
    estimatedMinutes: 20,
  },
  {
    sourceKey: "s1-d4-4",
    sprintName: "Sprint 1",
    title: "Count number of Nice subarrays",
    notes: "Sprint 1 - Day 4",
    date: planDate(9, 29),
    dayNumber: 4,
    difficulty: "Medium",
    estimatedMinutes: 4,
  },
  {
    sourceKey: "s1-d4-5",
    sprintName: "Sprint 1",
    title: "Power Set",
    notes: "Sprint 1 - Day 4",
    date: planDate(9, 29),
    dayNumber: 4,
    difficulty: "Medium",
    estimatedMinutes: 20,
  },
  {
    sourceKey: "s1-d4-6",
    sprintName: "Sprint 1",
    title: "Generate Parentheses",
    notes: "Sprint 1 - Day 4",
    date: planDate(9, 29),
    dayNumber: 4,
    difficulty: "Medium",
    estimatedMinutes: 22,
  },
  {
    sourceKey: "s1-d4-7",
    sprintName: "Sprint 1",
    title: "Letter Combinations of a Phone Number",
    notes: "Sprint 1 - Day 4",
    date: planDate(9, 29),
    dayNumber: 4,
    difficulty: "Medium",
    estimatedMinutes: 12,
  },
  {
    sourceKey: "s1-d4-8",
    sprintName: "Sprint 1",
    title: "Combination Sum",
    notes: "Sprint 1 - Day 4",
    date: planDate(9, 29),
    dayNumber: 4,
    difficulty: "Medium",
    estimatedMinutes: 16,
  },
  {
    sourceKey: "s1-d4-9",
    sprintName: "Sprint 1",
    title: "Combination Sum II",
    notes: "Sprint 1 - Day 4",
    date: planDate(9, 29),
    dayNumber: 4,
    difficulty: "Medium",
    estimatedMinutes: 15,
  },
  {
    sourceKey: "s1-d4-10",
    sprintName: "Sprint 1",
    title: "Subsets II",
    notes: "Sprint 1 - Day 4",
    date: planDate(9, 29),
    dayNumber: 4,
    difficulty: "Medium",
    estimatedMinutes: 21,
  },
];
